declare module "react-timeseries-charts";
declare module "react-grid-gallery";
declare module "get-sheet-done";
declare module "react-image-gallery"
declare module "react-slick"
declare module "react-image-magnify"
declare module "react-image-magnifiers"
declare module "react-custom-scrollbars"
declare module "lodash"
