export enum AuthorDisciplineFilter {
  ARTDESIGN = "ARTDESIGN",
  ARCHITECTURE = "ARCHITECTURE",
  LANDSCAPE = "LANDSCAPE",
  OTHER = "OTHER",
  ARTDESIGN_2016 = "ARTDESIGN_2016",
  ARTDESIGN_2018 = "ARTDESIGN_2018",
  ARTDESIGN_2020 = "ARTDESIGN_2020",
  ARCHITECTURE_2016 = "ARTDESIGN_2016",
  ARCHITECTURE_2018 = "ARTDESIGN_2018",
  ARCHITECTURE_2020 = "ARTDESIGN_2020",
  OTHER_2016 = "OTHER_2016",
  OTHER_2018 = "OTHER_2018",
  OTHER_2020 = "OTHER_2020",
  LANDSCAPE_2016 = "LANDSCAPE_2016",
  LANDSCAPE_2018 = "LANDSCAPE_2018",
  LANDSCAPE_2020 = "LANDSCAPE_2020",
}

export enum FilterState {
  SOLO = "SOLO",
  DEACTIVATED = "DEACTIVATED",
  DEFAULT = "DEFAULT",
}
// export

export enum EventLevel {
  national = "national",
  state = "state",
  city = "city",
  international = "international",
  NA = "NA",
}

export enum FilterGroup {
  STUDENTS_2016 = "STUDENTS_2016",
  STUDENTS_2018 = "STUDENTS_2018",
  STUDENTS_2020 = "STUDENTS_2020",
  BUILT_TOPIC = "BUILT_TOPIC",
  ECONOMIC_TOPIC = "ECONOMIC_TOPIC",
  NATURAL_TOPIC = "NATURAL_TOPIC",
  POLITICAL_TOPIC = "POLITICAL_TOPIC",
  SOCIAL_TOPIC = "SOCIAL_TOPIC",
  EQUITY_THEME = "EQUITY_THEME",
  ACCESS_THEME = "ACCESS_THEME",
  DIVERISTY_THEME = "DIVERISTY_THEME",
  NONE = "NONE",
  ARCHITECTURE_STUDENTS = "ARCHITECTURE",
  ARTDESIGN_STUDENTS = "ARTDESIGN",
  OTHER_STUDENTS = "OTHER",
  LANDSCAPE_STUDENTS = "LANDSCAPE",
}

export enum EventType {
  DATE = "DATE",
  RANGE = "RANGE",
}

//Correspond to the subtopic value for a student
export enum MapSubTopic {
  //BUILT ENVIRONMENT
  BUILDINGS = "BUILDINGS",
  TRANSPORTATION = "TRANSPORTATION",
  INFRASTR = "INFRASTR",
  //NATURAL ENVIRONMENT
  GREENSPACE = "GREENSPACE",
  HYDROLOGY = "HYDROLOGY",
  POLLUTION = "POLLUTION",
  //SOCIAL-CULTURAL ENVIRONMENT
  EDUCATION = "EDUCATION",
  HEALTHSAFETY = "HEALTHSAFETY",
  RACEGEN = "RACEGEN",
  //POLITICAL ENVIRONMENT
  GOVERMENT = "GOVERMENT",
  POLICY = "POLICY",
  CIVICENG = "CIVICENG",
  //ECONOMIC ENVIRONMENT
  WORK = "WORK",
  URBANDEV = "URBANDEV",
  PROPERTY = "PROPERTY",
}
// export enum MapSubTopic {
//   //BUILT ENVIRONMENT
//   BE_BUILDINGS = "BUILDINGS",
//   BE_TRANSPORTATION = "TRANSPORTATION",
//   BE_INFRASTR = "INFRASTR",
//   //NATURAL ENVIRONMENT
//   NE_GREENSPACE = "GREENSPACE",
//   NE_HYDROLOGY = "HYDROLOGY",
//   NE_POLLUTION = "POLLUTION",
//   //SOCIAL-CULTURAL ENVIRONMENT
//   SE_EDUCATION = "EDUCATION",
//   SE_HEALTH = "HEALTH",
//   SE_RACEGEN = "RACEGEN",
//   //POLITICAL ENVIRONMENT
//   PE_GOV = "GOV",
//   PE_POLICY = "POLICY",
//   PE_CIVICENG = "CIVICENG",
//   //ECONOMIC ENVIRONMENT
//   EE_WORK = "WORK",
//   EE_URBANDEV = "URBANDEV",
//   EE_PROPERTY = "PROPERTY",
// }

export enum Topic {
  BE = "BE",
  SE = "SE",
  PE = "PE",
  EE = "EE",
  NE = "NE",
}

export enum GalleryFilterType {
  TOPIC,
  DISCIPLINE,
  THEME,
  FILTERGROUP,
  FILTERGROUP_TOPIC,
  FILTERGROUP_YEAR,
}
export enum ThemeCategoryFilter {
  EQUITY = "EQUITY",
  ACCESS = "ACCESS",
  DIVERSITY = "DIVERSITY",
}
