export enum AuthorDisciplineFilter{
    ARTDESIGN ="ARTDESIGN",
    ARCHITECTURE = "ARCHITECTURE",
    LANDSCAPE = "LANDSCAPE",
    OTHER = "OTHER",
    ARTDESIGN_2016 ="ARTDESIGN_2016",
    ARTDESIGN_2018 ="ARTDESIGN_2018",
    ARTDESIGN_2020 ="ARTDESIGN_2020",
    ARCHITECTURE_2016 ="ARTDESIGN_2016",
    ARCHITECTURE_2018 ="ARTDESIGN_2018",
    ARCHITECTURE_2020 ="ARTDESIGN_2020",
    OTHER_2016 ="OTHER_2016",
    OTHER_2018 ="OTHER_2018",
    OTHER_2020 ="OTHER_2020",
    LANDSCAPE_2016 ="LANDSCAPE_2016",
    LANDSCAPE_2018 ="LANDSCAPE_2018",
    LANDSCAPE_2020 ="LANDSCAPE_2020",
}

export enum EventLevel{
  national = "national",
  state = "state", 
  city = "city",
  
}

export enum EventType{
  DATE = "DATE",
  RANGE = "RANGE",
}
export enum TopicSubCategoryFilter{
  BE_HOUSING = "HOUSING",
  BE_TRANSPORTATION = "TRANSPORTATION",
  BE_ENERGY = "ENERGY",
  EE_COSTOFLIVING = "COSTOFLIVING",
  EE_HOUSINGMARKET = "HOUSINGMARKET",
  EE_COMMERCE = "COMMERCE",
  NE_GREENSPACE = "GREENSPACE",
  NE_POLLUTION = "POLLUTION",
  NE_WATER = "WATER",
  PE_GOVERMENT = "GOVERMENT",
  PE_LEGISLATION = "LEGISLATION",
  PE_ACTIVISM = "ACTIVISM",
  SE_EDUCATION = "EDUCATION",
  SE_HEALTH = "HEALTH",
  SE_POPULATION = "POPULATION",
}

export enum GalleryFilterType{
  TOPIC,
  DISCIPLINE,
  THEME,
}
export enum ClassYearFilter {
  
}
export enum ThemeCategoryFilter{
    EQUITY = "EQUITY",
    ACCESS = "ACCESS",
    DIVERSITY = "DIVERSITY",
}

